import assert from 'node:assert/strict';
import {findPdfMatches,searchPattern} from '../searchIndex';
import {mappedPdfText,textCacheLimits} from '../textCache';
import {mergeNoteRects,rotateNoteRect} from '../annotationGeometry';
import {allocatePdfCanvas,availablePdfPixels,pdfCanvasStats,prunePdfCanvases,releasePdfCanvas} from '../canvasPool';
const plain={caseSensitive:false,mode:'plain'} as const;
assert.deepEqual(findPdfMatches('İ ABC abc','İ',plain),[{charOffset:0,length:1}]);
assert.deepEqual(findPdfMatches('İ','i',plain),[{charOffset:0,length:1}],'partial case-fold expansion still highlights the original glyph');
assert.equal(findPdfMatches('ABC abc','ABC',{...plain,caseSensitive:true}).length,1);
assert.deepEqual(findPdfMatches('HT-2026-1234 HT-2026-5678','HT-2026-????',{...plain,mode:'wildcard'}),[{charOffset:0,length:12},{charOffset:13,length:12}]);
assert.deepEqual(findPdfMatches('abc abc','a.c',{...plain,mode:'regex'}),[{charOffset:0,length:3},{charOffset:4,length:3}]);
assert.deepEqual(findPdfMatches('😀x','(?=.)',{...plain,mode:'regex'}),[],'zero-width Unicode expressions terminate');
assert.throws(()=>findPdfMatches('abc','[',{...plain,mode:'regex'}));
assert.throws(()=>searchPattern('a'.repeat(513),'regex'));
assert.equal(findPdfMatches('***','*',plain).length,3,'plain punctuation stays literal');
const content={items:[{str:''},{str:'  A  B'},{type:'beginMarkedContent'},{str:'İ test'},{str:'\n C'}]} as unknown as Parameters<typeof mappedPdfText>[0];
assert.deepEqual(mappedPdfText(content),{text:'  A  B İ test \n C',items:[{index:1,start:0,end:6},{index:3,start:7,end:13},{index:4,start:14,end:17}]});
assert.deepEqual(textCacheLimits(10),{pages:32,bytes:4194304});
assert.equal(textCacheLimits(500).pages,128);assert.equal(textCacheLimits(500).bytes,16777216);
const rects=[{x:0.1,y:0.1,width:0.1,height:0.02},{x:0.201,y:0.101,width:0.1,height:0.02},{x:0.5,y:0.1,width:0.1,height:0.02},{x:0.1,y:0.2,width:0.1,height:0.02}];
const merged=mergeNoteRects(rects,0.002,0.002);assert.equal(merged.length,3,'merge neighbours without crossing columns or lines');
assert.equal(mergeNoteRects([rects[0],rects[0]],0.002,0.002).length,1,'selection duplicate rects collapse');
const restored=rotateNoteRect(rotateNoteRect(rects[0],0,90),90,0);for(const key of ['x','y','width','height'] as const)assert.ok(Math.abs(restored[key]-rects[0][key])<1e-10);
let domReads=0;
const canvas={width:0,height:0,get isConnected(){domReads++;return false;},closest:()=>null} as unknown as HTMLCanvasElement;
assert.ok(allocatePdfCanvas(canvas,100,100));assert.equal(pdfCanvasStats().pixels,10000);
for(let i=0;i<50;i++)availablePdfPixels();assert.equal(domReads,0,'budget queries never inspect DOM');
assert.ok(allocatePdfCanvas(canvas,200,100));assert.equal(pdfCanvasStats().pixels,20000,'resize replaces accounting');
prunePdfCanvases();assert.equal(domReads,1);assert.equal(pdfCanvasStats().pixels,0);
releasePdfCanvas(canvas);assert.equal(pdfCanvasStats().pixels,0,'release is idempotent');
console.log('PASS PDF enhancement units: mapped offsets, matching, cache limits, rect merging and constant-time canvas accounting');

const {pageSize}=await import('../metadata');
let start!:()=>void,release!:()=>void;
const started=new Promise<void>(resolve=>{start=resolve;}),gate=new Promise<void>(resolve=>{release=resolve;});
const doc={getPage:async()=>{start();await gate;return {getViewport:()=>({width:500,height:300})};}} as unknown as import('pdfjs-dist').PDFDocumentProxy;
const abort=new AbortController();
const warmer=pageSize(doc,1,5,abort.signal),reader=pageSize(doc,1,1);
const cancelled=assert.rejects(warmer,{name:'AbortError'});
await started;abort.abort();release();await cancelled;assert.deepEqual(await reader,{width:500,height:300},'cancelling prewarm must not cancel a shared reader');
console.log('PASS PDF metadata: prewarm abort cannot cancel another dimension reader');
